api/pom.xml

Signed-off-by: Tomas Kraus <tomas.kraus@oracle.com>

Parent pom updated to 1.0.2. Fixed profiles and plugin dependencies.

---

api/pom.xml

Use correct version of common annotations

---

api/pom.xml
api/test/README.txt
api/test/setup.sh

Fixes #46: artifactId should be jakarta.xml.ws-api

---

api/pom.xml
api/test/README.txt
api/test/setup.sh

[EE4J_8] Fixes #46: artifactId should be jakarta.xml.ws-api

---

api/pom.xml

final cleanup

---

api/pom.xml

Release branch can be deleted after merge.

Merge 2.3.2 release information into EE4J_8 branch.

---

CONTRIBUTING.md
NOTICE.md
README.md

 #58: Change project name to Jakarta XML Web Services

---

api/pom.xml
api/src/main/java/javax/xml/ws/handler/package-info.java
api/src/main/java/javax/xml/ws/handler/soap/package-info.java
api/src/main/java/javax/xml/ws/http/package-info.java
api/src/main/java/javax/xml/ws/package-info.java
api/src/main/java/javax/xml/ws/soap/package-info.java
api/src/main/java/javax/xml/ws/spi/http/package-info.java
api/src/main/java/javax/xml/ws/spi/package-info.java
api/src/main/java/javax/xml/ws/wsaddressing/package-info.java
api/src/main/jdk9/module-info.java
spec/pom.xml

#62: javadocs update

---

api/pom.xml

JWS 1.1.2 integration

---

CONTRIBUTING.md
NOTICE.md
README.md
api/copyright-exclude
api/pom.xml
api/src/main/java/javax/xml/ws/handler/package-info.java
api/src/main/java/javax/xml/ws/handler/soap/package-info.java
api/src/main/java/javax/xml/ws/http/package-info.java
api/src/main/java/javax/xml/ws/package-info.java
api/src/main/java/javax/xml/ws/soap/package-info.java
api/src/main/java/javax/xml/ws/spi/http/package-info.java
api/src/main/java/javax/xml/ws/spi/package-info.java
api/src/main/java/javax/xml/ws/wsaddressing/package-info.java
api/src/main/javadoc/doc-files/speclicense.html
api/src/main/jdk9/module-info.java
api/src/main/resources/javax/xml/ws/wsdl_customizationschema_2_0.xsd
spec/LICENSE
spec/pom.xml
spec/src/assembly/assembly.xml

* javadocs
* copyrights
* readme

various fixes

---

api/copyright-exclude
etc/scripts/maven.incl.sh

Also fixed copyright excludes.

Fix copyright headers with version update

---

api/pom.xml
spec/src/main/asciidoc/license-efsl.adoc

fix revmark

---

api/src/main/java/javax/xml/ws/WebServiceRef.java
api/src/main/java/javax/xml/ws/spi/Provider.java
api/src/main/java/javax/xml/ws/wsaddressing/W3CEndpointReferenceBuilder.java

fix references to Java EE in javadoc

---

api/pom.xml

integrate new annotation-api 1.3.5

---

api/pom.xml
api/src/main/java/module-info.java

Fixed OSGi headers
Fixed module definition

Update build plugin versions

---

api/pom.xml
api/src/main/java/javax/xml/ws/WebServiceRef.java
api/src/main/java/module-info.java

remove explicit dependency on java.annotation

---

api/src/main/java/javax/xml/ws/WebServiceContext.java
api/src/main/java/javax/xml/ws/WebServiceRef.java

fix see tags

---

api/pom.xml

update build plugins, remove timestamps

---

api/pom.xml

update parent, plugins, fix spec version

---

spec/pom.xml
spec/src/assembly/assembly.xml
spec/src/main/asciidoc/xml-ws-spec.adoc
spec/src/main/asciidoc/xml-ws.adoc

fix the spec name

---

api/pom.xml
api/src/main/java/jakarta/xml/ws/Provider.java
api/src/main/java/module-info.java

bump spec version, fix module name, minor corrections

---

api/pom.xml
api/src/main/java/jakarta/xml/ws/Provider.java
api/src/main/java/jakarta/xml/ws/Service.java
api/src/main/java/jakarta/xml/ws/handler/soap/SOAPMessageContext.java
api/src/main/java/jakarta/xml/ws/soap/SOAPBinding.java
api/src/main/java/jakarta/xml/ws/soap/SOAPFaultException.java
api/src/main/java/jakarta/xml/ws/spi/ServiceDelegate.java
api/src/main/java/module-info.java

Integrate jakarta soap api 2.0.0-rc1 and jakarta jws api 3.0.0-rc1

---

api/pom.xml
api/src/main/java/jakarta/xml/ws/EndpointReference.java
api/src/main/java/jakarta/xml/ws/LogicalMessage.java
api/src/main/java/jakarta/xml/ws/Service.java
api/src/main/java/jakarta/xml/ws/handler/soap/SOAPMessageContext.java
api/src/main/java/jakarta/xml/ws/spi/ServiceDelegate.java
api/src/main/java/jakarta/xml/ws/wsaddressing/W3CEndpointReference.java
api/src/main/java/jakarta/xml/ws/wsaddressing/package-info.java
api/src/main/java/module-info.java
api/test/runtests.sh

Integrate jaxb-api 3.0.0-rc1

---

api/src/main/resources/jakarta/xml/ws/wsdl_customizationschema_3_0.xsd

define schema for jakartaee

---

api/pom.xml

JWS API needs to be on the compile scope now

---

CONTRIBUTING.md

#122: Update CONTRIBUTING.md for Specification Project's repositories

---

enterprise-ws-spec/src/main/asciidoc/Security.adoc

The pull request is opened to Jakarta-ize chapter 9 of Jakarta Enterprise Web services specification.

Updates to Jakarta Enterprise Web Services spec Chapter 9

---

enterprise-ws-spec/pom.xml
enterprise-ws-spec/src/main/asciidoc/ClientProgrammingModel.adoc
enterprise-ws-spec/src/main/asciidoc/Deployment.adoc
enterprise-ws-spec/src/main/asciidoc/DeploymentDescriptors.adoc
enterprise-ws-spec/src/main/asciidoc/EnterpriseWebServices.adoc
enterprise-ws-spec/src/main/asciidoc/Handlers.adoc
enterprise-ws-spec/src/main/asciidoc/OptionalSupportForJ2EE1.3Platforms.adoc
enterprise-ws-spec/src/main/asciidoc/Overview.adoc
enterprise-ws-spec/src/main/asciidoc/References.adoc
enterprise-ws-spec/src/main/asciidoc/RelationshipToOtherJavaStandards.adoc
enterprise-ws-spec/src/main/asciidoc/RevisionHistory.adoc
enterprise-ws-spec/src/main/asciidoc/Security.adoc
enterprise-ws-spec/src/main/asciidoc/ServerProgrammingModel.adoc
enterprise-ws-spec/src/main/asciidoc/enterprise-ws-spec.adoc

Fixes #129, fixes #127  (among other things)

Finalize spec document for ent ws

---

enterprise-ws-spec/src/main/asciidoc/license-efsl.adoc

fix cp years

---

spec/pom.xml
spec/src/main/asciidoc/ch04-client_apis.adoc
spec/src/main/asciidoc/ch09-handler_framwork.adoc
spec/src/main/asciidoc/license-efsl.adoc

fix pointers to images in the spec

---

spec/pom.xml
spec/src/main/asciidoc/XMLWebServices.adoc
spec/src/main/asciidoc/appB-change_log.adoc
spec/src/main/asciidoc/ch01-introduction.adoc
spec/src/main/asciidoc/ch02-wsdl_to_java_mapping.adoc
spec/src/main/asciidoc/ch03-java_to_wsdl_mapping.adoc
spec/src/main/asciidoc/ch04-client_apis.adoc
spec/src/main/asciidoc/ch05-service_apis.adoc
spec/src/main/asciidoc/ch06-core_apis.adoc
spec/src/main/asciidoc/ch07-annotations.adoc
spec/src/main/asciidoc/ch08-customizations.adoc
spec/src/main/asciidoc/ch09-handler_framwork.adoc
spec/src/main/asciidoc/ch10-soap_binding.adoc
spec/src/main/asciidoc/ch11-http_binding.adoc
spec/src/main/asciidoc/xml-ws-spec.adoc

fix spec name,
add missing appendixes

Update spec chapter 1,2

---

spec/src/main/asciidoc/ch02-wsdl_to_java_mapping.adoc
spec/src/main/asciidoc/ch03-java_to_wsdl_mapping.adoc
spec/src/main/asciidoc/ch04-client_apis.adoc

Update spec chapter 3, 4

---

spec/src/main/asciidoc/XMLWebServices.adoc
spec/src/main/asciidoc/appB-change_log.adoc
spec/src/main/asciidoc/ch03-java_to_wsdl_mapping.adoc
spec/src/main/asciidoc/ch05-service_apis.adoc
spec/src/main/asciidoc/ch06-core_apis.adoc
spec/src/main/asciidoc/ch07-annotations.adoc
spec/src/main/asciidoc/ch08-customizations.adoc
spec/src/main/asciidoc/ch09-handler_framwork.adoc
spec/src/main/asciidoc/ch10-soap_binding.adoc
spec/src/main/asciidoc/ch11-http_binding.adoc

Update spec chapter 5-11

---

spec/src/main/asciidoc/appC-bibliography.adoc
spec/src/main/asciidoc/ch01-introduction.adoc
spec/src/main/asciidoc/ch02-wsdl_to_java_mapping.adoc
spec/src/main/asciidoc/ch03-java_to_wsdl_mapping.adoc
spec/src/main/asciidoc/ch05-service_apis.adoc

fix up pointers to related specs

---

api/pom.xml
api/src/main/java/jakarta/xml/ws/spi/FactoryFinder.java
api/src/main/java/jakarta/xml/ws/spi/Provider.java

Update for 3.0.1

---

api/src/main/java/jakarta/xml/ws/AsyncHandler.java

allow to use lambdas as handler implementation

annotate AsyncHandler with @FunctionalInterface

---

api/src/main/java/jakarta/xml/ws/spi/FactoryFinder.java

Change logging in the FactoryFinder class

Change logging in the FactoryFinder class

---

api/src/main/java/jakarta/xml/ws/RespectBindingFeature.java
api/src/main/java/jakarta/xml/ws/soap/AddressingFeature.java
api/src/main/java/jakarta/xml/ws/soap/MTOMFeature.java
api/src/main/java/jakarta/xml/ws/spi/FactoryFinder.java
api/src/main/java/jakarta/xml/ws/spi/Provider.java
api/src/main/java/jakarta/xml/ws/wsaddressing/W3CEndpointReference.java
spec/src/main/asciidoc/appB-change_log.adoc
spec/src/main/asciidoc/ch06-core_apis.adoc

Add getters to W3CEndpointReference, update implementation discovery

---

etc/jenkins/release.sh
etc/scripts/nexus.incl.sh

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

Jenkins release job update
